spring:
  data:
    mongodb:
      uri: mongodb+srv://shubhamshelar9860:feTqnCZmJnykHLdN@cluster0.u87gjew.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal